baseurl: "/"
title: "Stackbit Personal Theme"
init_js: "js/init.js"
page_load_js: "js/page-load.js"
page_unload_js: "js/page-unload.js"
params:
  layout_type: boxed
  style: classic
  palette: red
  mode: light
  base_font: serif
  header:
    title: Personal Theme
    logo: "images/logo.svg"
    logo_alt: Alyvia logo
    has_primary_nav: true
    primary_nav_links:
      - label: FAQ
        url: /faq
        style: link
      - label: About
        url: /about
        style: link
      - label: Contact me
        url: /contact
        style: link
    has_secondary_nav: false
    has_anncmnt: false
  footer:
    logo: "images/logo.svg"
    logo_alt: Alyvia logo
    has_primary_nav: true
    primary_nav_links:
      - label: About
        url: /about
        style: link
      - label: FAQ
        url: /faq
        style: link
      - label: Contact me
        url: /contact
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Style Guide
        url: /style-guide
        style: link
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: https://twitter.com/
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: Facebook
        url: https://www.facebook.com/
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - label: Instagram
        url: https://www.instagram.com/
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with <a href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank" rel="noopener">Stackbit</a>. Create yours <a href="https://app.stackbit.com/create?theme=personal&utm_source=deployed-footer" target="_blank" rel="noopener">now</a>
sass:
  input_file: sass/main.scss
  output_file: css/main.css
  indentWidth: 4
  outputStyle: expanded
  precision: 10
templates:
  body_class: "layout-{{ site.params.layout_type }} style-{{ site.params.style }} palette-{{ site.params.palette }} mode-{{ site.params.mode }} font-{{ site.params.base_font }}"
